DROP TABLE IF EXISTS post;

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author TEXT NOT NULL,
	title TEXT NOT NULL,
	text TEXT NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
